HAST-158: Vitis hardware implementation composer
Lombiq/Hastlayer-Hardware-Framework---Vitis pull request #1
Opened 2020-10-31 00:59 UTC by sarahelsaig

2020-10-31 01:01 UTC, sarahelsaig commented on rtl/src/scripts/gen_xo.tcl
> +else {
Ez azért kell, mert a Hastlayer az `src` working directory alól futtatja a `vivado`-t.

2020-10-31 22:10 UTC, Piedone requested changes

2020-10-31 22:10 UTC, Piedone commented on rtl/Makefile
> +	$(VIVADO) -mode batch -source ./src/scripts/gen_xo.tcl -tclargs $(XCLBIN)/hastip.$(TARGET).xo $(TARGET) $(DEVICE)
Ez miért nem kell?

2020-10-31 22:10 UTC, Piedone commented on rtl/src/scripts/gen_xo.tcl
>      puts "ERROR: Program \"$::argv0\" requires 4 arguments!\n"
```suggestion
    puts "ERROR: Program \"$::argv0\" requires 3 arguments!\n"
```

2020-10-31 22:24 UTC, sarahelsaig commented on rtl/Makefile
> +	$(VIVADO) -mode batch -source ./src/scripts/gen_xo.tcl -tclargs $(XCLBIN)/hastip.$(TARGET).xo $(TARGET) $(DEVICE)
Félrevezetőnek találtam, hogy paraméter legyen a gen_xo.tcl-ben mert igazából nem szerkeszthető semilyen szinten. A "hastip" kernel név több helyen hard codeolva van itt is meg a Hastlayer driverben is. Például:
- Makefile 43-ik sorában: "CLFLAGS += --connectivity.sp **hastip**_1.buffer:$(MEMTYPE)[0:0]"
- OpenClCommunicationService.cs 21. sorában: `public const string KernelName = "hastip";`
- gen_xo.tcl 54. sorában ami ebben a PR-ben nem változott: "package_xo -xo_path ${xoname} -kernel_name **hastip** -ip_directory ./packaged_kernel_${suffix} -kernel_xml ./src/xml/kernel.xml"

2020-10-31 22:43 UTC, Piedone commented on rtl/Makefile
> +	$(VIVADO) -mode batch -source ./src/scripts/gen_xo.tcl -tclargs $(XCLBIN)/hastip.$(TARGET).xo $(TARGET) $(DEVICE)
De a kernel neve szerintem ez. Ugye most nem a Hast_IP nevű VHDL entity-ről beszélünk, hanem az azt wrappelő Vitis RTL kernelről. Ezt inkább beszéld meg Ernővel.

2020-10-31 22:51 UTC, sarahelsaig commented on rtl/Makefile
> +	$(VIVADO) -mode batch -source ./src/scripts/gen_xo.tcl -tclargs $(XCLBIN)/hastip.$(TARGET).xo $(TARGET) $(DEVICE)
> De a kernel neve szerintem ez.

Mi az az "ez"?

Itt nem történt semmilyen funkcionális változás, csak a "hastip" név a gen_xo.tlc-ben fixálva lett az olvashatóság javítása és a hamis konfigurálhatóság illúziójának elkerülése végett. Mert amúgy eddig itt a Makefile-ban volt konstans szóval ugyanaz az eredmény és ha megpróbáltad volna átírni másra akkor crash.

2020-10-31 22:52 UTC, Piedone commented on rtl/Makefile
> +	$(VIVADO) -mode batch -source ./src/scripts/gen_xo.tcl -tclargs $(XCLBIN)/hastip.$(TARGET).xo $(TARGET) $(DEVICE)
Ja értem, OK.

2020-10-31 22:52 UTC, Piedone approved these changes

2020-11-01 20:48 UTC, Piedone requested changes

2020-11-01 20:48 UTC, Piedone commented on Hast.Vitis.Abstractions.HardwareFramework.csproj
> +      <None Update="rtl\src\IP\Hast_IP.vhd" LinkBase="config\" CopyToOutputDirectory="PreserveNewest" Link="HardwareFramework\%(RecursiveDir)%(Filename)%(Extension)" />
Ezeknél nem lehet inkább wildcardokat megadni, hogy az egész mappára érvényes legyen?

2020-11-01 20:48 UTC, Piedone commented on Hast.Vitis.Abstractions.HardwareFramework.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Légyszi dokumentáld ebben a projectben MD-be, hogy erre miért van szükség.

2020-11-01 21:07 UTC, sarahelsaig commented on Hast.Vitis.Abstractions.HardwareFramework.csproj
> +      <None Update="rtl\src\IP\Hast_IP.vhd" LinkBase="config\" CopyToOutputDirectory="PreserveNewest" Link="HardwareFramework\%(RecursiveDir)%(Filename)%(Extension)" />
De, lehet! SO-n azt mondták az CopyToOutputDirectory egy fájlra van ezért meg se próbáltam.

2020-11-01 21:07 UTC, sarahelsaig commented on Hast.Vitis.Abstractions.HardwareFramework.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
ok

2020-11-01 23:11 UTC, Piedone approved these changes

2020-11-04 17:56 UTC, Piedone approved these changes

2020-11-04 23:13 UTC, merged