HAST-174: Create a 32-bit binary and other Zynq fixes
Lombiq/Hastlayer-Hardware-Framework---Vitis pull request #2
Opened 2021-10-01 02:09 UTC by DAud-IcI

HAST-174

2021-10-01 02:26 UTC, sarahelsaig commented on rtl/Makefile.Zynq
> +# Dumping help
Ez a fájl csak "for reference" van itt, nem használjuk.

2021-10-01 02:26 UTC, sarahelsaig commented on rtl/src/scripts/fpga-bit-to-bin.py
> +#!/usr/bin/python
please no python code review 😄

2021-10-01 02:27 UTC, sarahelsaig commented on Hast.Vitis.Abstractions.HardwareFramework.csproj
> +      <None Update="platforms\**\*.*" CopyToOutputDirectory="PreserveNewest" Link="HardwareFramework\%(RecursiveDir)%(Filename)%(Extension)" />
Itt ez az egyetlen változtatás ami saját. A többi az Ernő által küldött platform fájlok és scriptek.

2021-10-01 13:41 UTC, Piedone requested changes

2021-10-01 13:41 UTC, Piedone commented on platforms/TE0715-04-30-1C/sw/trenz_te0715_04_30_1c_base/boot/generic.readme
> +2. Set boot mode to SD
Ezzel nekünk nem kell foglalkozni, ez csak a generic legenerált Readme, ugye?

2021-10-01 13:41 UTC, Piedone commented on rtl/Makefile.Zynq
> +# Dumping help
Légyszi akkor valahova ezt dokumentáld.

2021-10-01 13:41 UTC, Piedone commented on rtl/src/scripts/fpga-bit-to-bin.py
> +#!/usr/bin/python
Pedig értek hozzá, mert egyszer ültem valaki mellett, aki látott már ilyen kódot.

2021-10-01 13:46 UTC, sarahelsaig commented on platforms/TE0715-04-30-1C/sw/trenz_te0715_04_30_1c_base/boot/generic.readme
> +2. Set boot mode to SD
Igen.

2021-10-01 14:01 UTC, Piedone commented on platforms/TE0715-04-30-1C/sw/trenz_te0715_04_30_1c_base/boot/generic.readme
> +2. Set boot mode to SD
Cool.

2022-01-26 00:08 UTC, Piedone commented on rtl/Makefile.Zynq
> +# Dumping help
Ez kimaradt.

2022-01-26 00:08 UTC, Piedone requested changes
Lásd comment.

2022-01-26 00:50 UTC, DAud-IcI commented on rtl/Makefile.Zynq
> +# Dumping help
Nem maradt ki, [itt](https://github.com/Lombiq/Hastlayer-Hardware-Framework---Vitis/pull/2/commits/14552c766be92c4165611003963fd70f7c19ae84#diff-1550ec65ac92f65817fc28928dfef526912b5f52356ff43651369bae92f56031R12) ez akar az lenni:
>The rtl directory contains Makefiles which you could feasibly use to build projects C++ style. More importantly **we use them to track changes when translating a new version of the C++ prototype implementations into the C# build providers**.

2022-01-26 00:56 UTC, DAud-IcI commented on rtl/Makefile.Zynq
> +# Dumping help
Valóban nem szuper egyértelmű. Tovább részleteztem ugyanott:
> In other words we don't actually use the _/rtl/Makefile_ and _/rtl/Makefile.Zynq_ in our code or build process directly. Consider it documentation if you know how to use make.

2022-01-26 01:04 UTC, Piedone approved these changes

2022-01-26 21:16 UTC, merged